---
- :name: Vegemite Scroll
  :code: VS5
  :packs:
    - :number_of_unit: 2
      :price: 6.99
    - :number_of_unit: 7
      :price: 8.99
    - :number_of_unit: 8
      :price: 8.99
- :name: Blueberry Muffin
  :code: MB11
  :packs:
    - :number_of_unit: 2
      :price: 9.95
    - :number_of_unit: 5
      :price: 16.95
    - :number_of_unit: 8
      :price: 24.95
- :name: Croissant
  :code: CF
  :packs:
    - :number_of_unit: 3
      :price: 5.95
    - :number_of_unit: 5
      :price: 9.95
    - :number_of_unit: 9
      :price: 16.99